### ISSUE TITLE
Black screen on wake-up after log-in

### ISSUE THREAD

**Issue by jammons** [pigigaldi/Pock#163] opened 2019-07-11 18:26 UTC
**Describe the bug**
When using the sleep button from within Pock, when wake my computer, I log in, then just see a black screen with either a cursor or a spinning wheel of death. Waiting several minutes nothing happens. 

Restarting my machine, I still get the same effect after login (the black screen), but closing the laptop and reopening it, then waiting 20 seconds or so, it does finally start up properly. I reproduced this twice with these steps.

Sleeping using the normal touchbar button (without Pock running) or with the apple menu sleep option (with Pock running) causes no problems.

**How to reproduce**
```
1. Start Pock
2. Enable sleep button
3. Click sleep button
4. Attempt to re-awaken the computer,
```

**Expected behavior**
I expect the computer to wake from sleep.

**Crashlog**
I can't find any crash reports. Maybe because I had to restart to get my system back to working?

**Versions:**
 - macOS version: 10.13.6
 - Pock version:  0.5.3

**Comment by pigigaldi** [comment] 2019-09-30 20:03
I'm closing this since I can't reproduce this behavior with the provided steps.
Feel free to re-open this issue if you're still facing this problem.
Thanks!

**Closed by pigigaldi** 2019-09-30 20:03 UTC
Labels: bug
