### ISSUE TITLE
clock time syncing lost with version 0.6

### ISSUE THREAD

**Issue by tegotha** [pigigaldi/Pock#215] opened 2019-08-23 09:58 UTC
Clock (both 12 and 24 hr format) does not sync with system time. triggering the show/don't show tickboxes updates the time. Time shown is always time of widget loading/pock startup

 - macOS version: 10.14.6
 - Pock version:  0.6

**Comment by nilsolofsson** [comment] 2019-08-24 09:56
Found that restarting pock solved the issue for me

**Comment by tegotha** [comment] 2019-08-26 08:38
@nilsolofsson  i can concur restarting Pock fixed clock sync

**Comment by lompabo** [comment] 2019-08-28 07:51
I can confirm the bug. Restarting seems to fix it for a while (a short while, in my case) and then the clock is stuck again.

**Comment by raunaqkapoor** [comment] 2019-08-29 02:46
Facing the same bug, restarting only updates the time to the moment of widget load, but stagnates there. No updates afterwards.

**Comment by isofia** [comment] 2019-08-29 07:21
same bug

**Comment by schnphil** [comment] 2019-09-01 21:22
Same Bug. Restart or switching from 24hr to 12hr format will only help for a few minutes

**Comment by hvdklauw** [comment] 2019-09-09 12:30
Closing my laptop (sleep) and reopening seems to be when things break.

**Comment by emilianomassai** [comment] 2019-10-02 16:52
Same bug for me.. Is there any possibility that it will be fixed at some point? Thank you for the pick app, it fulfills the lacks of Apple’s Touch Bar project!

**Comment by pigigaldi** [comment] 2019-10-02 17:02
@emilianomassai yep, a fix will come during this week. 🌳

**Comment by emilianomassai** [comment] 2019-10-02 17:04
Thank you!

**Comment by RonanMacF** [comment] 2019-10-07 12:44
Same issue

**Closed** 2019-10-09 20:25 UTC
Labels: bug

**Comment by emilianomassai** [comment] 2019-10-09 20:34
HI there! Did you find out how to solve those bugs? Let me know! Thank you!

**Comment by pigigaldi** [comment] 2019-10-09 21:04
@emilianomassai version `0.6.2` is now available and include this fix.
Thanks for your patience! 🙏

**Comment by emilianomassai** [comment] 2019-10-09 23:20
Thank you! I also have some ideas if you want to improve your pock project. Maybe you can add a more functional wifi icon where you can tap to turn on or off the wifi. The same could be for the BT. What do you think?

**Comment by emilianomassai** [comment] 2019-10-09 23:38
I'm testing the app but since I installed the new version it is using a lot of CPU..
