### ISSUE TITLE
Time is not synced with the current time.

### ISSUE THREAD

**Issue by praveen-me** [pigigaldi/Pock#93] opened 2019-06-23 15:29 UTC
The battery percentage and time is not synced with the system.

1. Go to pock customization setting and add the date and time to the touch bar.

It should be synced with the system date and time and battery section

#### Touchbar
![touchbar](https://user-images.githubusercontent.com/29889620/59978423-afc79a00-95f9-11e9-8b00-3ae56af290ce.jpg)

#### Desktop
<img width="1431" alt="Desktop Screen" src="https://user-images.githubusercontent.com/29889620/59978447-de457500-95f9-11e9-9b54-8712a3f7cf4a.png">

**Comment by pigigaldi** [comment] 2019-06-23 16:21
Closing this since is a duplicate of #90

**Closed by pigigaldi** 2019-06-23 16:21 UTC
Labels: bug

**Comment by rbatra396** [comment] 2019-08-07 04:54
> Closing this since is a duplicate of #90

I cannot access the settings for pock anyone else have this issue
