### ISSUE TITLE
widget time module can't sync with system time

### ISSUE THREAD

**Issue by isofia** [pigigaldi/Pock#221] opened 2019-08-29 06:49 UTC
widget time module can't sync with system time

widget time stopped at 13:30

**Comment by willvousden** [comment] 2019-09-17 12:13
I have the same problem.  It shows the time that I added the widget to the touch bar.  It seems to update the time whenever I change the widget's preferences.

Other things (e.g., battery level) seem unaffected.

**Comment by apairofcleats** [comment] 2019-09-24 03:13
Same problem as above, time on touchbar doesnt keep up with system time.

**Comment by pigigaldi** [comment] 2019-10-04 08:02
Duplicate of #215

**Closed by pigigaldi** 2019-10-04 08:02 UTC
Labels: bug
