### ISSUE TITLE
Calendar icon doesn't update

### ISSUE THREAD

**Issue by kopf** [pigigaldi/Pock#119] opened 2019-07-01 05:33 UTC
**Describe the bug**
The icon for the OS X Calendar updates in the dock to show the current date (e.g. "Jul 1"). This does not happen in pock.

**To Reproduce**
* Add Calendar to the dock
* Run pock
* Wait a day
* Observe that the icon in the dock has been updated to the current date, but in pock it's displaying yesterday's date

**Expected behavior**
The Calendar icon in pock should be up-to-date

**Additional context**
Possibly related to #90

**Comment by pigigaldi** [comment] 2019-07-06 06:23
Nope, this is not related to #90; it just picks the Calendar app default icon.
I still need to figure this out.

**Comment by mbauman** [comment] 2019-10-04 15:32
Duplicate of #36.

**Closed** 2019-10-05 06:30 UTC
Labels: enhancement
